spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anirudh09041/ConfigRepository
          default-label: master
#          clone-on-start: true
server:
  port: 8888
